version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    expose:
      - ${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    expose:
      - ${DB_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on: 
      - api

volumes: 
  data: {}
